import React, { useEffect, useState } from 'react';
import { PauseCircle, PlayCircle, RefreshCw, SearchCheck, ShieldCheck } from 'lucide-react';
import { blogGscAction, fetchBlogGscReport } from './api';

type GscUrlRow = {
  publication_id:string; article_id?:string|null; article_title?:string|null; article_slug?:string|null; url:string;
  publication_confirmed_at?:string|null; last_inspected_at?:string|null; next_inspection_at?:string|null;
  knowledge_state?:string|null; action_state?:string|null; action_reason?:string|null;
};

type Report = {
  state:any; lastRun?:any;lastScheduledRun?:any;activeRun?:any;preparedReleases?:any[]; urls:GscUrlRow[]; runs:any[]; runsPage?:{page:number;pageSize:number;total:number|null};
  automation?:{operator_paused?:boolean;pause_reason?:string|null;changed_at?:string|null;revision?:number;changed_by_user_id?:string|null};
  infrastructure?:{enabled:boolean;configured_schedule:string;schedule_expression:string};
};

function dateTime(value?:string|null){if(!value)return 'Indisponível';const d=new Date(value);return Number.isNaN(d.getTime())?'Indisponível':new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(d);}
function label(value?:string|null){const map:Record<string,string>={indexed:'Indexada',excluded:'Não indexada / excluída',unknown_to_google:'Ainda desconhecida pelo Google',inconclusive:'Inconclusivo',waiting:'Aguardar',stable:'Estável',action_required:'Ação necessária',baseline_required:'Primeiro envio pendente',confirmed:'Envio confirmado pelo Google',unchanged:'Sitemap sem mudanças',uncertain:'Resultado incerto',failed_transient:'Falha temporária',blocked:'Bloqueada',running:'Em andamento',succeeded:'Concluída',failed:'Falhou',skipped:'Não executada'};return value?map[value]||value.replaceAll('_',' '):'Indisponível';}
function reason(value?:string|null){if(!value)return 'Nenhuma ação registrada.';const reasons:Record<string,string>={succeeded:'A verificação do dia já foi concluída',running:'A verificação existente ainda está em andamento',uncertain:'A execução anterior tem resultado incerto e exige conferência',blocked:'A execução anterior está bloqueada e precisa de revisão',failed:'Uma tentativa anterior falhou; aguarde a janela de nova tentativa',skipped:'A operação já foi registrada e não será repetida',missing_after_conflict:'A operação existente ainda não pôde ser consultada',lost_recovery_race:'Outra execução assumiu a verificação',gsc_full_permission_required:'A conta precisa de permissão completa no Google Search Console',sitemap_hash_mismatch:'O sitemap publicado difere da versão esperada',gsc_submission_older_than_expected:'O Google confirmou um envio anterior ao esperado'};if(reasons[value])return reasons[value];if(value==='inspection_failed')return 'Falha ao inspecionar; uma nova tentativa poderá ser feita.';if(value==='gsc_response_inconclusive')return 'O Google ainda não trouxe resposta conclusiva.';if(value==='not_indexed_after_14_days')return 'URL não indexada após 14 dias da publicação.';if(value==='operator_paused'||value==='operator_paused_before_submit')return 'Acompanhamento pausado no painel.';if(value==='execution_window_reached')return 'A verificação foi encerrada no limite de tempo; o restante segue na próxima rotina.';if(value.startsWith('gsc_blocker:'))return `Bloqueio técnico: ${value.slice(12).replaceAll('_',' ').toLowerCase()}.`;return 'Motivo não reconhecido; consulte os detalhes da execução.';}

export const BlogGscStatus:React.FC=()=>{
  const [report,setReport]=useState<Report|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [page,setPage]=useState(1);const [pauseReason,setPauseReason]=useState('');
  const load=async(targetPage=page)=>{setLoading(true);setError('');try{setReport(await fetchBlogGscReport(targetPage,10));setPage(targetPage);}catch(e){setError(e instanceof Error?e.message:'Status Blog/GSC indisponível.');}finally{setLoading(false);}};
  useEffect(()=>{void load(1);},[]);
  const mutate=async(payload:Record<string,unknown>)=>{setBusy(true);setError('');setNotice('');try{const result=await blogGscAction(payload);if(payload.action==='set-automation')localStorage.removeItem('karyne_blog_gsc:automation');if(payload.action==='run-now')setNotice(result?.status==='skipped'?`Verificação não repetida: ${reason(result?.reason)}.`:`Verificação: ${label(result?.status)}.`);else if(payload.action==='confirm-publication')setNotice('Conferência da publicação concluída e registrada.');else setNotice('Controle atualizado e registrado.');await load(page);}catch(e){setError(e instanceof Error?e.message:'Operação não concluída.');}finally{setBusy(false);}};
  const toggleAutomation=()=>{const stored=localStorage.getItem('karyne_blog_gsc:automation');let payload:Record<string,unknown>|null=null;if(stored){try{payload=JSON.parse(stored);}catch{setError('Não foi possível ler a operação de controle preservada.');return;}}if(!payload){payload={action:'set-automation',operationKey:crypto.randomUUID(),expectedRevision:report?.automation?.revision||0,paused:!report?.automation?.operator_paused,reason:report?.automation?.operator_paused?'':pauseReason};localStorage.setItem('karyne_blog_gsc:automation',JSON.stringify(payload));}void mutate(payload!);};
  const paused=Boolean(report?.automation?.operator_paused);const total=report?.runsPage?.total;const hasNext=typeof total==='number'?page*10<total:(report?.runs?.length||0)===10;
  return <div className="space-y-4 [&_button:focus-visible]:outline-2 [&_button:focus-visible]:outline-offset-2 [&_button:focus-visible]:outline-[#565E48] [&_a:focus-visible]:outline-2 [&_a:focus-visible]:outline-[#565E48]">
    <section className="bg-[#FEFEFE] border border-[#E4DFD9] rounded-2xl p-4 md:p-5">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[13px] font-semibold text-[#565E48] inline-flex items-center gap-2"><SearchCheck size={15}/> Google Search Console</div><p className="text-[12px] text-[#2B1B0A]/55 mt-1">O que o painel sabe sobre as páginas no Google. Falta de informação não conta como zero nem como página indexada.</p></div><button aria-label="Atualizar dados sem executar automação" onClick={()=>void load(page)} disabled={loading||busy} className="p-2 rounded-xl border border-[#E4DFD9] hover:bg-[#F6F0E9] disabled:opacity-50" title="Atualizar dados, sem executar automação"><RefreshCw size={15} className={loading?'animate-spin':''}/></button></div>
      {error&&<div className="mt-3 text-sm text-[#8B2312] bg-[#8B2312]/8 border border-[#8B2312]/20 rounded-xl p-3">{error}</div>}{notice&&<div className="mt-3 text-sm text-[#365B32] bg-[#365B32]/8 border border-[#365B32]/20 rounded-xl p-3">{notice}</div>}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-3 mt-4 text-sm">
        <div><div className="text-[11px] uppercase text-[#2B1B0A]/45">Infraestrutura</div><div className="mt-1 font-medium">{report?.infrastructure?report.infrastructure.enabled?'Habilitada':'Desabilitada':'Indisponível'}</div></div>
        <div><div className="text-[11px] uppercase text-[#2B1B0A]/45">Agenda configurada</div><div className="mt-1 font-medium">{report?.infrastructure?.configured_schedule||'Indisponível'}</div></div>
        <div><div className="text-[11px] uppercase text-[#2B1B0A]/45">Pausa operacional</div><div className={`mt-1 font-medium ${paused?'text-[#8B2312]':'text-[#365B32]'}`}>{report?.automation?paused?'Pausada':'Ativa':'Indisponível'}</div></div>
        <div><div className="text-[11px] uppercase text-[#2B1B0A]/45">Última execução observada</div><div className="mt-1 font-medium">{dateTime(report?.lastRun?.updated_at)}</div></div>
      </div>
      {report?.automation&&<div className="mt-3 text-[12px] text-[#2B1B0A]/60">{paused?`Motivo: ${report.automation.pause_reason||'não informado'} · `:''}Alteração: {dateTime(report.automation.changed_at)}<details className="mt-1"><summary>Quem registrou a pausa ou retomada</summary>{report.automation.changed_by_user_id||'Indisponível'}</details></div>}<div className="mt-3 text-sm text-[#2B1B0A]/65">Última execução agendada: {dateTime(report?.lastScheduledRun?.updated_at)} · {label(report?.lastScheduledRun?.status)}</div>{report?.activeRun&&<div className="mt-3 rounded-xl border border-[#D8D1C9] p-3 text-sm">Há uma verificação em andamento desde {dateTime(report.activeRun.started_at||report.activeRun.created_at)}. Pausar impede as próximas execuções; a atual pode concluir. Atualize os dados para conferir o resultado.</div>}
      <div className="mt-4 flex flex-col lg:flex-row gap-3 lg:items-end">
        <div className="flex-1"><label className="text-[11px] uppercase text-[#2B1B0A]/45">Motivo ao pausar</label><input aria-label="Motivo ao pausar a automação" value={pauseReason} onChange={e=>setPauseReason(e.target.value)} placeholder="Ex.: revisão de configuração antes da próxima rotina" className="mt-1 w-full rounded-xl border border-[#D8D1C9] bg-white px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-[#565E48]/25"/></div>
        <div className="flex flex-wrap gap-2">
          <button disabled={busy||!report?.automation||(!paused&&pauseReason.trim().length<3)} onClick={toggleAutomation} className="inline-flex items-center gap-2 rounded-xl border border-[#D8D1C9] bg-white px-3 py-2.5 text-sm font-medium disabled:opacity-40">{paused?<><PlayCircle size={16}/>Retomar automação</>:<><PauseCircle size={16}/>Pausar automação</>}</button>
          <button disabled={busy||paused||Boolean(report?.activeRun)||report?.infrastructure?.enabled!==true} onClick={()=>void mutate({action:'run-now'})} className="inline-flex items-center gap-2 rounded-xl bg-[#222D19] text-white px-3 py-2.5 text-sm font-medium disabled:opacity-40"><ShieldCheck size={16}/>Executar verificação agora</button>
        </div>
      </div>
      <p className="text-[11px] text-[#2B1B0A]/40 mt-3">Este botão roda a mesma verificação diária automática. Se ela já rodou hoje, não roda de novo. O horário automático não muda por aqui.</p>
    </section>

    <section className="bg-white border border-[#E4DFD9] rounded-2xl p-4"><h2 className="text-sm font-semibold text-[#565E48]">Sitemap</h2><div className="grid md:grid-cols-3 gap-3 mt-3 text-sm"><div>Estado: {report?.state?label(report.state.last_submit_status):'Indisponível'}</div><div>Última tentativa: {dateTime(report?.state?.last_submit_attempt_at)}</div><div>Último envio confirmado: {dateTime(report?.state?.last_submit_confirmed_at)}</div><div>Envio informado pelo Google: {dateTime(report?.state?.last_google_submitted_at)}</div></div>{report?.state?.sitemap_url&&<a href={report.state.sitemap_url} target="_blank" rel="noreferrer" className="inline-block mt-3 underline text-sm text-[#565E48]">Consultar sitemap publicado</a>}{report?.state?.last_error_code&&<p className="mt-2 text-sm text-[#8B2312]">{reason(report.state.last_error_code)}</p>}<details className="mt-3 text-[12px] text-[#2B1B0A]/50"><summary>Detalhes do envio</summary><div>Identificador do sitemap confirmado: {report?.state?.last_confirmed_sitemap_sha256||'Indisponível'}</div><div>Identificador da tentativa: {report?.state?.last_submit_attempt_sha256||'Indisponível'}</div><div>Último erro: {report?.state?.last_error_code||'não registrado'} · {dateTime(report?.state?.last_error_at)}</div></details></section>
    {!!report?.preparedReleases?.length&&<section className="bg-white border border-[#E4DFD9] rounded-2xl p-4"><h2 className="font-medium">Publicações preparadas para conferência</h2><p className="mt-1 text-[12px] text-[#2B1B0A]/55">A conferência consulta a página pública e registra o resultado para a versão preparada.</p>{report.preparedReleases.map(release=><div key={release.operation_key} className="mt-3 border-t border-[#E4DFD9] pt-3 flex flex-wrap gap-3 items-center"><a href={release.url||release.canonical_url||release.details_json?.canonical_url} target="_blank" rel="noreferrer" className="text-sm underline">Consultar artigo preparado</a><button disabled={busy||!release.operation_key} onClick={()=>void mutate({action:'confirm-publication',operationKey:release.operation_key})} className="text-sm rounded-xl border border-[#D8D1C9] px-3 py-2 disabled:opacity-40">Conferir publicação preparada</button></div>)}</section>}

    <section className="bg-[#FEFEFE] border border-[#E4DFD9] rounded-2xl overflow-hidden">
      <div className="px-4 py-3 border-b border-[#E4DFD9] text-[13px] font-semibold text-[#565E48]">URLs acompanhadas</div>
      <div className="overflow-x-auto"><table className="w-full min-w-[860px] text-[12px]"><thead><tr className="bg-[#F6F0E9] text-left uppercase tracking-wide text-[#2B1B0A]/45"><th className="px-3 py-2">Artigo</th><th className="px-3 py-2">Publicação confirmada</th><th className="px-3 py-2">Última inspeção</th><th className="px-3 py-2">Estado conhecido</th><th className="px-3 py-2">Próxima inspeção</th><th className="px-3 py-2">Ação</th></tr></thead><tbody className="divide-y divide-[#E4DFD9]">{(report?.urls||[]).filter(row=>{const filter=new URLSearchParams(window.location.search).get('blogStatus');return filter==='indexed'?row.knowledge_state==='indexed':filter==='action_pending'?row.action_state==='action_required':true;}).map(row=><tr key={row.publication_id}><td className="px-3 py-2.5"><div className="font-medium">{row.article_title||row.article_slug||row.url}</div><div className="text-[#2B1B0A]/40">{row.article_slug||row.url}</div></td><td className="px-3 py-2.5">{dateTime(row.publication_confirmed_at)}</td><td className="px-3 py-2.5">{dateTime(row.last_inspected_at)}</td><td className="px-3 py-2.5">{label(row.knowledge_state)}</td><td className="px-3 py-2.5">{dateTime(row.next_inspection_at)}</td><td className={row.action_state==='action_required'?'px-3 py-2.5 text-[#8B2312] font-medium':'px-3 py-2.5'}>{reason(row.action_reason)}{row.action_state==='action_required'&&<div className="flex flex-wrap gap-2 mt-2"><a href={row.url} target="_blank" rel="noreferrer" className="underline text-[#565E48]">Consultar página pública</a><a href={`/admin?tab=blog&blogSection=articles${row.article_id?`&blogArticle=${encodeURIComponent(row.article_id)}`:''}`} className="underline text-[#565E48]">Revisar artigo</a><a href={report?.state?.site_url?`https://search.google.com/search-console?resource_id=${encodeURIComponent(report.state.site_url)}`:'https://search.google.com/search-console'} target="_blank" rel="noreferrer" className="underline text-[#565E48]">Consultar no Google</a></div>}</td></tr>)}{!loading&&!(report?.urls||[]).length&&<tr><td colSpan={6} className="px-4 py-8 text-center text-[#2B1B0A]/45">Nenhuma URL acompanhada disponível.</td></tr>}</tbody></table></div>
    </section>

    <section className="bg-[#FEFEFE] border border-[#E4DFD9] rounded-2xl overflow-hidden">
      <div className="px-4 py-3 border-b border-[#E4DFD9] flex items-center justify-between"><div className="text-[13px] font-semibold text-[#565E48]">Histórico de execuções</div><div className="text-[11px] text-[#2B1B0A]/45">{typeof total==='number'?`${total} registros`:'total indisponível'}</div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-[12px]"><thead><tr className="bg-[#F6F0E9] text-left text-[#2B1B0A]/45"><th className="px-3 py-2">Quando</th><th className="px-3 py-2">Origem</th><th className="px-3 py-2">Tipo</th><th className="px-3 py-2">Resultado</th><th className="px-3 py-2">Tentativas</th></tr></thead><tbody className="divide-y divide-[#E4DFD9]">{(report?.runs||[]).map(run=><tr key={run.operation_key}><td className="px-3 py-2.5">{dateTime(run.updated_at)}</td><td className="px-3 py-2.5">{run.trigger_source==='manual'?'Manual':run.trigger_source==='scheduled'?'Agendada':'Legado / não registrado'}</td><td className="px-3 py-2.5">{run.run_kind}</td><td className="px-3 py-2.5">{label(run.status)}{run.status==='skipped'&&<div className="mt-1">{reason(run.details_json?.reason||run.reason)}</div>}</td><td className="px-3 py-2.5">{run.attempts??'Indisponível'}</td></tr>)}</tbody></table></div>
      <div className="px-4 py-3 flex justify-between border-t border-[#E4DFD9]"><button disabled={page<=1||loading} onClick={()=>void load(page-1)} className="text-sm px-3 py-2 rounded-xl border border-[#D8D1C9] disabled:opacity-40">Anterior</button><span className="text-[12px] text-[#2B1B0A]/50 self-center">Página {page}</span><button disabled={!hasNext||loading} onClick={()=>void load(page+1)} className="text-sm px-3 py-2 rounded-xl border border-[#D8D1C9] disabled:opacity-40">Próxima</button></div>
    </section>
  </div>;
};
